"""
Generate HTML report dari hasil scan
"""

from datetime import datetime
from pathlib import Path


def generate_html_report(username: str, results: list[dict], output_path: str):
    found = [r for r in results if r["found"]]
    not_found = [r for r in results if not r["found"] and not r.get("error")]
    errors = [r for r in results if r.get("error")]

    # Group found by category
    categories: dict[str, list] = {}
    for r in found:
        cat = r.get("category", "Other")
        categories.setdefault(cat, []).append(r)

    found_rows = ""
    for cat, items in sorted(categories.items()):
        for r in sorted(items, key=lambda x: x["platform"]):
            found_rows += f"""
            <tr>
                <td><span class="badge badge-{_cat_class(cat)}">{cat}</span></td>
                <td><strong>{r['platform']}</strong></td>
                <td><a href="{r['url']}" target="_blank">{r['url']}</a></td>
                <td><span class="status found">✓ Found</span></td>
            </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>OSINT Report — {username}</title>
<style>
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0d1117; color: #c9d1d9; min-height: 100vh; }}
  .header {{ background: #161b22; border-bottom: 1px solid #30363d; padding: 2rem; }}
  .header h1 {{ font-size: 1.5rem; color: #58a6ff; }}
  .header .target {{ font-size: 2rem; font-weight: 700; color: #e6edf3; margin: 0.5rem 0; }}
  .header .meta {{ font-size: 0.85rem; color: #8b949e; }}
  .stats {{ display: flex; gap: 1rem; padding: 1.5rem 2rem; background: #161b22; border-bottom: 1px solid #30363d; }}
  .stat {{ background: #0d1117; border: 1px solid #30363d; border-radius: 8px; padding: 1rem 1.5rem; flex: 1; text-align: center; }}
  .stat .num {{ font-size: 2rem; font-weight: 700; }}
  .stat .label {{ font-size: 0.8rem; color: #8b949e; margin-top: 4px; }}
  .found-num {{ color: #3fb950; }}
  .total-num {{ color: #58a6ff; }}
  .err-num {{ color: #f85149; }}
  .container {{ padding: 2rem; }}
  .section-title {{ font-size: 1rem; font-weight: 600; color: #e6edf3; margin: 1.5rem 0 0.75rem; border-left: 3px solid #3fb950; padding-left: 0.75rem; }}
  table {{ width: 100%; border-collapse: collapse; background: #161b22; border: 1px solid #30363d; border-radius: 8px; overflow: hidden; }}
  th {{ background: #21262d; color: #8b949e; font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.05em; padding: 0.75rem 1rem; text-align: left; }}
  td {{ padding: 0.75rem 1rem; border-top: 1px solid #21262d; font-size: 0.9rem; }}
  tr:hover td {{ background: #1c2128; }}
  a {{ color: #58a6ff; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .status {{ padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }}
  .status.found {{ background: #1a3a1f; color: #3fb950; }}
  .badge {{ padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; }}
  .badge-dev {{ background: #1a2a3a; color: #58a6ff; }}
  .badge-social {{ background: #2a1a3a; color: #d2a8ff; }}
  .badge-gaming {{ background: #1a3a2a; color: #3fb950; }}
  .badge-creative {{ background: #3a2a1a; color: #e3b341; }}
  .badge-forum {{ background: #3a1a1a; color: #f85149; }}
  .badge-tech {{ background: #1a2a3a; color: #79c0ff; }}
  .badge-indonesia {{ background: #3a1a1a; color: #ffa657; }}
  .badge-professional {{ background: #2a2a3a; color: #a5d6ff; }}
  footer {{ text-align: center; padding: 2rem; color: #8b949e; font-size: 0.8rem; border-top: 1px solid #30363d; margin-top: 2rem; }}
</style>
</head>
<body>

<div class="header">
  <h1>🔍 OSINT Username Report</h1>
  <div class="target">@{username}</div>
  <div class="meta">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} · {len(results)} platforms scanned</div>
</div>

<div class="stats">
  <div class="stat"><div class="num total-num">{len(results)}</div><div class="label">Platforms Scanned</div></div>
  <div class="stat"><div class="num found-num">{len(found)}</div><div class="label">Found</div></div>
  <div class="stat"><div class="num" style="color:#8b949e">{len(not_found)}</div><div class="label">Not Found</div></div>
  <div class="stat"><div class="num err-num">{len(errors)}</div><div class="label">Errors</div></div>
</div>

<div class="container">
  <div class="section-title">✓ Found on {len(found)} platforms</div>
  <table>
    <thead><tr><th>Category</th><th>Platform</th><th>URL</th><th>Status</th></tr></thead>
    <tbody>{found_rows if found_rows else '<tr><td colspan="4" style="text-align:center;color:#8b949e;padding:2rem">Username not found on any platform</td></tr>'}</tbody>
  </table>
</div>

<footer>
  Generated by OSINT Username Checker · For educational purposes only<br>
  Created by <a href="https://muhamadakbarfadilah.my.id/" target="_blank" style="color:#58a6ff">Akbar Fadilah</a>
  · Founder &amp; Co-Founder at <a href="https://afdatech.com/" target="_blank" style="color:#58a6ff">Afda Technology Solutions</a>
</footer>
</body>
</html>"""

    Path(output_path).write_text(html, encoding="utf-8")


def _cat_class(category: str) -> str:
    mapping = {
        "Developer": "dev",
        "Social": "social",
        "Gaming": "gaming",
        "Creative": "creative",
        "Forum": "forum",
        "Tech": "tech",
        "Indonesia": "indonesia",
        "Professional": "professional",
    }
    return mapping.get(category, "dev")
